# only trigger build through main or release branch
trigger:
  tags:
    include:
      - release@*
  branches:
    include:
      - master

name: $(Build.SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r) 

variables:
  vmImage: 'ubuntu-latest'
  projectName: 'Southport.Messaging.Email.Core'
  buildConfiguration: 'Release'

stages:
#------------------------Build Library - Main------------------------------------------
- stage: 'BuildLibraryMain'
  displayName: 'Build - Library'
  dependsOn: []
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
    artifactName: 'dev-library'
  jobs:
  - template: 'DevOps/build.yml'

#------------------------Build Library - Release------------------------------------------
- stage: 'BuildLibraryRelease'
  displayName: 'Build - Library'
  dependsOn: []
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
  variables:
    artifactName: 'release-library'
  jobs:
  - template: 'DevOps/build.yml'

#------------------------Deploy LIBRARY------------------------------------------
- stage: 'PublishLibraryRelease'
  displayName: 'Deploy to prod (release)'
  dependsOn: 'BuildLibraryRelease'
  condition: succeeded()
  variables:
    artifact: 'release-library'
  jobs:
  - template: 'DevOps/deploy.yml'  
  parameters:    
    environment: 'nuget-publish-approval'
